server:
  port: 8860

dubbo:
  application:
    name: blog-article
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 12220
  scan:
    base-packages: co.jratil.blogarticle.service

spring:
  application:
    name: blog-article

  datasource:
    #    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #    username: root
    #    password: ratil123
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: ratil
      password: ratil
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小
      initial-size: 5
      # 最小空闲数
      min-idle: 5
      #最大活动数量
      max-active: 30
      #最大等待时间
      max-wait: 6000

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    root: info
    org:
      springframework: info
    co:
      jratil:
        blogarticle: info

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  default-count: true