server:
  port: 8860

dubbo:
  application:
    name: blog-article
  registry:
    address: zookeeper://47.115.6.99:4362
  protocol:
    name: dubbo
    port: 12220
  scan:
    base-packages: co.jratil.blogarticle.service
  config-center:
    timeout: 10000

spring:
  application:
    name: blog-article

  datasource:
    druid:
      url: jdbc:mysql://120.79.172.32:33066/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: ratil
      password: ratil123
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小
      initial-size: 5
      # 最小空闲数
      min-idle: 5
      #最大活动数量
      max-active: 30
      #最大等待时间
      max-wait: 6000

  redis:
    database: 0
    host: 47.115.6.99
    port: 26379
    #password: ratil123

    jedis:
      pool:
        max-active: 30
        max-wait: 1000
        max-idle: 10
        min-idle: 5
    timeout: 6000

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    root: info
    org:
      springframework: info
    co:
      jratil:
        blogarticle: info

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  default-count: true
