server:
  port: 8871

dubbo:
  application:
    name: blog-sms
  registry:
    address: zookeeper://47.115.6.99:4362
  metadata-report:
    address: zookeeper://47.115.6.99:4362
  protocol:
    name: dubbo
    port: 12231
  provider:
    timeout: 120000
  scan:
    base-packages: co.jratil.blogsms.service

spring:
  application:
    name: blog-sms


# 邮件设置
mail:
  region_id: cn-hangzhou
  from:
    alias: 不错博客
    account_name: blog@jratil.co

logging:
  level:
    root: info
    org:
      springframework: info