server:
  port: 8866

spring:
  application:
    name: blog-user
  dubbo:
    protocol:
      port: 21881
    server: true
    registry: zookeeper://localhost:2181

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: ratil
      password: ratil123
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小
      initial-size: 5
      # 最小空闲数
      min-idle: 5
      #最大活动数量
      max-active: 30
      #最大等待时间
      max-wait: 6000

  redis:
    database: 0
    host: localhost
    port: 6379
    #    password: ratil123

    jedis:
      pool:
        max-active: 30
        max-wait: 1000
        max-idle: 10
        min-idle: 5
    timeout: 6000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath*:mapper/*.xml

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  default-count: true

logging:
  level:
    root: info
    org:
      springframework: info