server:
  port: 8000

dubbo:
  application:
    name: blog-controller
  registry:
    address: zookeeper://47.115.6.99:4362
  metadata-report:
    address: zookeeper://47.115.6.99:4362
  protocol:
    name: dubbo
    port: 12222
  scan:
    base-packages: co.jratil.blogcontroller.controller
  config-center:
    timeout: 10000

spring:
  application:
    name: blog-controller

  datasource:
    druid:
        url: jdbc:mysql://120.79.172.32:33066/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: ratil
      password: ratil123
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小
      initial-size: 5
      # 最小空闲数
      min-idle: 5
      #最大活动数量
      max-active: 30
      #最大等待时间
      max-wait: 6000

# 分页插件
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#  default-count: true

swagger:
  ui-config:
    operations-sorter: alpha

logging:
  level:
    root: info
    com:
      alibaba:
        dubbo: debug